version: "3"

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "80:8080"
    networks:
      - app-network

  database:
    container_name: database
    image: mongo:latest
    environment:
      - NUME_VAR:VALOARE
    ports:
      - "27018:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge